[project]
name = "vcc-context-pair-xgb"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "numpy==2.5.3",
    "scipy==1.18.1",
    "pandas==3.0.6",
    "h5py==3.16.0",
    "pyarrow",
    "wandb==0.30.0",
    "anndata==0.13.4",
    "vcc-cli==0.2.1",
    "xgboost==3.3.0",
]

[tool.uv]
package = false
